# Generated by Django 5.0.6 on 2024-06-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='Введите название жанра', max_length=15, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание товара')),
                ('image', models.FileField(help_text='Выберите изображение товара', upload_to='img/', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Укажите цену товара', max_digits=8, verbose_name='Цена')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(help_text='Введите имя продавца', max_length=15, verbose_name='Имя продавца')),
                ('last_name', models.CharField(help_text='Введите фамилию продавца', max_length=15, verbose_name='Фамилия продавца')),
                ('phone_number', models.IntegerField(help_text='Введите номер телефона', verbose_name='Номер телефона')),
                ('state', models.ManyToManyField(help_text='Укажите состояние товара', related_name='goods', to='goods.state', verbose_name='Состояние')),
            ],
        ),
    ]
