# Generated by Django 5.0.6 on 2024-06-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_goods_state_goods_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='state',
            field=models.CharField(default='Б/у', help_text='Введите название жанра', max_length=15, verbose_name='Название жанра'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
