# Generated by Django 5.0.6 on 2024-06-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goods_state_delete_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='state',
            field=models.CharField(default='Б/у', help_text='Укажите состояние товара', max_length=15, verbose_name='Состояние товара'),
        ),
    ]
