# Generated by Django 5.0.6 on 2024-06-29 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_goods_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(help_text='Введите название жанра', max_length=15, verbose_name='Название жанра')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='state',
            field=models.ForeignKey(help_text='Укажите состояние товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.state', verbose_name='Состояние'),
        ),
    ]
