# Generated by Django 5.0.6 on 2024-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_goods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.FileField(help_text='Выберите изображение товара', upload_to='img/', verbose_name='Изображение товара'),
        ),
    ]
