# Generated by Django 5.0.6 on 2024-07-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_goods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.FileField(blank=True, help_text='Выберите изображение товара', upload_to='img/', verbose_name='Изображение товара'),
        ),
    ]
