# Generated by Django 5.0.6 on 2024-07-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_goods_created_on_alter_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='email',
            field=models.EmailField(blank=True, help_text='Введите почту продавца', max_length=100, null=True, verbose_name='Почта продавца'),
        ),
    ]
