# Generated by Django 5.0.6 on 2024-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_alter_goods_email_alter_goods_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='email',
            field=models.EmailField(blank=True, help_text='Введите почту продавца', max_length=100, null=True, verbose_name='Почта продавца'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='first_name',
            field=models.CharField(help_text='Введите имя продавца', max_length=15, verbose_name='Имя продавца'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='last_name',
            field=models.CharField(help_text='Введите фамилию продавца', max_length=15, verbose_name='Фамилия продавца'),
        ),
    ]
