# Generated by Django 5.0.6 on 2024-07-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_goods_email_alter_goods_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='email',
            field=models.EmailField(blank=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x0000022323FBC700>', help_text='Введите почту продавца', max_length=100, null=True, verbose_name='Почта продавца'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='first_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000022323FBC5E0>', help_text='Введите имя продавца', max_length=15, verbose_name='Имя продавца'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.FileField(blank=True, help_text='Выберите изображение товара', null=True, upload_to='static/img/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='last_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x0000022323FBC670>', help_text='Введите фамилию продавца', max_length=15, verbose_name='Фамилия продавца'),
        ),
    ]
